server:
  port: 8888
  address: 0.0.0.0


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    name: mysql80
    url: jdbc:mysql://127.0.0.1:3306/base_mall?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #下面这两个配置，可以在每次连接的时候判断一些连接是否有效
    druid.test-on-borrow: true
    druid.test-while-idle: true

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    pool:
      jedis:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0


path:
  uploadFolder:
    img: D:/liuJavaProject/baseProject/src/localData/
  tmpFile: D:/liuJavaProject/baseProject/src/tmpFile/
  testSourceFile: D:/liuJavaProject/baseProject/src/tmpFile/test.txt
  testSourcePath: D:/liuJavaProject/baseProject/src/tmpFile
  entityPath: D:/liuJavaProject/baseProject/src/main/java/com/common/dao/entity
  entityJsonPath: D:/liuJavaProject/baseProject/src/main/java/com/common/dao/entity/entityJsonBean

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.scrapy.helloscrapy.entity  # 注意：对应实体类的路径

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false
  params: count=countSql

#################################################日志####################################################
logging:
  level:
    com:
      common:
        dao:
          mapper: DEBUG
      scrapy:
        helloscrapy:
          controller: WARN

